server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.1.105:8848
    gateway:
      discovery:
        locator:
          # 默认为false，设为true开启通过微服务创建路由的功能，即可以通过微服务名访问服务
          # http://localhost:8888/mall-order/order/findOrderByUserId/1
          enabled: false
      # 是否开启网关
      enabled: true
      #设置路由：路由id、路由到微服务的uri、断言
      routes:
        - id: order_route  #路由ID，全局唯一，建议配合服务名
          #        #uri: http://localhost:8020  #目标微服务的请求地址和端口
          uri: lb://nacos-provider-order  #lb 整合负载均衡器ribbon,loadbalancer
          predicates:
            #        #Path路径匹配
            - Path=/order/**
  profiles:
    active: fat